Update readthedocs files
The-Academic-Observatory/observatory-platform pull request #412
Opened 2021-05-11 01:44 UTC by aroelo

Some minor fixes to the readthedocs files of the telescopes.
Also added the 'sphinx_markdown_tables' extension so the tables are rendered correctly.

2021-05-17 22:35 UTC, jdddog requested changes
Unfortunately  `sphinx_markdown_tables` has a GPLv3 license so we can't use it.

For the tables, for now, instead you can use `eval_rst` and use rst tables, see below for an example:

\```eval_rst
insert your rst table here
\```

2021-05-18 03:03 UTC, aroelo commented
> Unfortunately `sphinx_markdown_tables` has a GPLv3 license so we can't use it.
> 
> For the tables, for now, instead you can use `eval_rst` and use rst tables, see below for an example:
> 
> ```eval_rst
> insert your rst table here
> ```

Ah alright thanks. I did not realise that.
I'll try out the rst tables :-)

2021-05-18 23:48 UTC, jdddog reviewed
It looks good Aniek, it just needs to be rebased.

2021-05-20 01:53 UTC, jdddog approved these changes

2021-05-20 01:53 UTC, merged