Feature publisher workflow
The-Academic-Observatory/observatory-platform pull request #434
Opened 2021-06-15 05:58 UTC by rhosking

This work extends the existing onix_workflow. It creates tables in the oaebu dataset and data ready for export to elasticsearch in the oaebu_elastic datasets

2021-06-19 05:13 UTC, tuanchien reviewed
Good job. It's looking good.  Would be good to breakup that massive task creating lots of tables into separate functions for better isolation and testing.

It would also be good to have tests for the tables created in BQ.  I noticed some of the sql templates are quite large.  Not sure how feasible it is to break those up for easier testing, or whether one should just test the final output.

2021-06-21 01:03 UTC, rhosking commented on observatory-dags/observatory/dags/workflows/onix_workflow.py
> +        data_partner_datasets = {
yeah, looks good. Updated that bit

2021-06-21 01:07 UTC, rhosking commented
> It would also be good to have tests for the tables created in BQ. I noticed some of the sql templates are quite large. Not sure how feasible it is to break those up for easier testing, or whether one should just test the final output.

Some of those SQL scripts might be able to be improved, but without creating a trail of intermedia tables I'm not sure the logic can useful be broken apart any further. 

Just thinking through how to most usefully test the final actual output now. The workflow itself is better structured now though

2021-06-24 04:42 UTC, jdddog requested changes
It looks good Richard, I've just left a few small suggestions for changes.

2021-06-24 04:42 UTC, jdddog commented on observatory-dags/observatory/dags/database/sql/create_book_work_families.sql.jinja2
> +#
This file has no SQL in it, so better to delete it.

2021-06-24 04:42 UTC, jdddog commented on observatory-dags/observatory/dags/database/sql/create_book_works.sql.jinja2
> +{# Copyright 2020 Curtin University
This file has no SQL in it, so better to delete it.

2021-06-24 04:55 UTC, rhosking commented
@tuanchien @jdddog hopefully those changes address all your feedback. Jamie, I also added the skeleton for exporting to Elastic. All the needed variables should be nicely organised, and the tests have been updated to expect that DAG structure. It is just pending any updates/porting you do for those export utilities. It's not super pretty, but it's functionally fine and easier to adapt going forward

2021-06-24 06:11 UTC, tuanchien submitted a review, later dismissed

2021-06-24 07:52 UTC, jdddog approved these changes

2021-06-24 08:21 UTC, merged