Add pre-commit config & shell script
The-Academic-Observatory/observatory-platform pull request #469
Opened 2021-08-17 08:29 UTC by aroelo

Add pre-commit config & shell script to automate prefixing Jira issue key to commit message, closes #465

2021-08-18 21:29 UTC, jdddog requested changes
Did these files come from another project and do they have licenses?

2021-08-19 01:31 UTC, aroelo commented
> Did these files come from another project and do they have licenses?

No, the config file I created myself and the shell script was inspired by something from stackoverflow (without a license) and made some changes to it as well.

2021-08-19 05:53 UTC, jdddog commented
> No, the config file I created myself and the shell script was inspired by something from stackoverflow (without a license) and made some changes to it as well.

Ah ok thanks Aniek, it is probably OK because it is just a small script.

2021-08-19 22:05 UTC, jdddog approved these changes

2021-08-19 22:05 UTC, merged