Inf 40/create unpaywall data feed telescope
The-Academic-Observatory/observatory-platform pull request #498
Opened 2021-09-19 21:49 UTC by tuanchien

- bugfix: get_airflow_connection_url
- add get_airflow_connection_password
- add unzip_files function
- add find_replace_file  (sed cli replacement)

Using unzip/find_replace makes the platform slightly more portable compared to calling a cli program in bash. unzip is faster than cli + bash pipe equivalent.  find_replace is about same speed as sed + bash pipe.

2021-09-19 23:33 UTC, jdddog requested changes
Looks good Tuan, just a few small comments.

2021-09-19 23:33 UTC, jdddog commented on observatory-platform/observatory/platform/utils/file_utils.py
> +def unzip_files(*, file_list: List[str], output_dir: str = None):
Perhaps give this function a name that communicates that it is unzipping gzip files, e.g. gunzip_files

2021-09-19 23:33 UTC, jdddog commented on observatory-platform/observatory/platform/utils/proc_utils.py
> +    p = Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, executable="/bin/bash")
Maybe add `shell=True` as a keyword argument in run_bash_cmd so that it can be turned off if required.

2021-09-20 00:12 UTC, tuanchien commented
Changed:
- unzip_files to gunzip_files
- added run_cmd with shell/executable parameters if you just want to run a generic command

2021-09-20 02:00 UTC, jdddog approved these changes

2021-09-20 02:00 UTC, merged