Add api server isolation and db seeding
The-Academic-Observatory/observatory-platform pull request #562
Opened 2022-06-01 07:20 UTC by tuanchien

- Isolate local api server in its own docker container and own scripts
- Create framework for seeding api db data from scratch.

2022-06-02 01:19 UTC, jdddog requested changes
Hey Tuan, thanks for your PR, it looks pretty good. See below for comments.

Now that the apiserver has been separated, [entrypoint-airflow.sh.jinja2](https://github.com/The-Academic-Observatory/observatory-platform/blob/INF-406/INF-405/api_server_isolate_and_seed/observatory-platform/observatory/platform/docker/entrypoint-airflow.sh.jinja2) should be reverted back to how it was.

Could you also reformat the files with Black?

2022-06-06 08:39 UTC, tuanchien commented
liccheck needs to be turned off for markupsafe requirement for now.
Due to an api change, it seems like we need a more recent markupsafe version (>=2) but the current airflow version wants to pin it to 1.1.x.  Airflow 2.3.x will use markupsafe >=2 though.

2022-06-08 03:48 UTC, jdddog commented on observatory-platform/observatory/platform/docker/docker-compose.observatory.yml.jinja2
> +    volumes: *volumes
Might as well mount all volumes as it makes it tidier and we need them for installing from editable.

2022-06-08 03:48 UTC, jdddog commented on observatory-platform/observatory/platform/docker/docker-compose.observatory.yml.jinja2
> +      - API_URI={{api_uri}}
Cleaner to just set `API_URI` environment variable by itself. The api_uri variable is hard coded up the top in the local environment and set from an environment variable in the remote environment.

2022-06-08 03:48 UTC, jdddog commented on observatory-platform/observatory/platform/docker/seed_db.sh.jinja2
> +{% endfor %}
For all workflows packages call the seeding command exposed from setup.cfg.

2022-06-08 03:48 UTC, jdddog commented on observatory-platform/observatory/platform/docker/Dockerfile.package_install.jinja2
> +{% if install_deps %}
Added a variable that lets you stop dependencies being installed to make installation of the package quicker.

2022-06-08 03:48 UTC, jdddog commented on observatory-platform/observatory/platform/docker/docker-compose.observatory.yml.jinja2
> +{%- set api_uri="http://apiserver:5002" -%}
Can just be hard coded in local environment.

2022-06-08 03:48 UTC, jdddog commented on observatory-platform/observatory/platform/docker/docker-compose.observatory.yml.jinja2
> +{%- set api_uri="${API_URI}" -%}
In remote environment get from environment variable.

2022-06-13 05:25 UTC, jdddog approved these changes
Assuming that we have the tests passing it looks good to merge Tuan

2022-06-13 06:26 UTC, merged