Feature/Match on multiple keys for upserts and deletes in Bigquery.
The-Academic-Observatory/observatory-platform pull request #625
Opened 2023-07-06 06:11 UTC by alexmassen-hane

Add functionality to use either a singular string or list of strings of keys to match on for upserts and deletes in Biguqery. I have added this as a union of a string and list so we do not have to modify every workflow that uses these two functions. 

There's probably a much cleaner way of changing the jinja sql scripts for this. 
Please review and suggest other ways if possible.

2023-07-13 03:14 UTC, keegansmith21 submitted a review, later dismissed
Looks good! Thanks Alex! :+1:

2023-07-14 02:42 UTC, jdddog requested changes
Thanks Alex, it looks good, I just have a suggestion for simplifying the upsert and delete jinja templates.

2023-07-14 02:42 UTC, jdddog commented on observatory-platform/observatory/platform/sql/upsert_records.sql.jinja2
> +{% if keys|length == 1 %}
The jinja template could be simplified a little bit, I've also remove the newlines in the output (which were already there) with the minus signs:

```jinja2
MERGE `{{ main_table_id }}` main_table
USING `{{ upsert_table_id }}` upsert_table
ON (
  {%- for key in keys %}
  main_table.{{ key }}=upsert_table.{{ key }}{% if not loop.last %} AND{% endif %}
  {%- endfor %}
)
WHEN MATCHED THEN
  UPDATE SET
    {%- for col in columns %}
    main_table.{{ col }}=upsert_table.{{ col }}{% if not loop.last %},{% endif %}
    {%- endfor %}
WHEN NOT MATCHED THEN
  INSERT ROW
```

Then the output would be:
```sql
MERGE `my-project.bq_tests_c9b656431a145bdb8b9c22130bbf81f1.presidents` main_table
USING `my-project.bq_tests_c9b656431a145bdb8b9c22130bbf81f1.presidents_upserts` upsert_table
ON (
  main_table.name=upsert_table.name AND
  main_table.death_age=upsert_table.death_age
)
WHEN MATCHED THEN
  UPDATE SET
    main_table.name=upsert_table.name,
    main_table.death_age=upsert_table.death_age,
    main_table.date=upsert_table.date
WHEN NOT MATCHED THEN
  INSERT ROW
```

2023-07-14 02:42 UTC, jdddog commented on observatory-platform/observatory/platform/sql/delete_records.sql.jinja2
> +{% endif %}
To simplify the jinja template, try to use the approach in the suggestion for the upsert table here.

2023-07-21 01:28 UTC, jdddog approved these changes
Thanks Alex, the changes look good. I think unrelated tests are failing because they are flaky, lets see if they pass this time...

2023-07-21 02:45 UTC, merged